name: focus
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - scipy>=1.10.0
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - pip