# Example Diffusion Configuration
# Set method: "diffusion" to use standard Diffusion (default)

experiment:
  name: "diffusion_example"
  description: "Standard Diffusion with 128 base channels"
  created: "2024-10-29"

# Training method: "flow" or "diffusion"
method: "diffusion"  # Can also omit this line (diffusion is default)

# Data
data:
  maps_path: "/home/work/Cosmology/FOCUS/processed_data/maps_normalized.npy"
  params_path: "/home/work/Cosmology/FOCUS/processed_data/params_normalized.npy"
  train_split: 0.9
  num_workers: 4
  shuffle: true

# Model - Use SimpleUNet for Diffusion
model:
  from: "SimpleUNet"  # Standard diffusion U-Net
  in_channels: 1
  out_channels: 1
  cond_dim: 6
  base_channels: 128
  channel_mults: [1, 2, 4, 8]
  time_dim: 256  # Time embedding dimension

# Diffusion specific settings
diffusion:
  timesteps: 1000
  beta_start: 1.0e-4
  beta_end: 0.02
  schedule: "linear"

# Training
training:
  batch_size: 64
  num_epochs: 200
  lr: 1.0e-4
  weight_decay: 1.0e-4
  cfg_prob: 0.1  # 10% unconditional training for CFG
  sample_every: 1
  gradient_clip: 1.0
  
  # Optimizer
  optimizer: "adamw"
  
  # Scheduler: Plateau with warmup
  scheduler:
    name: "plateau"
    factor: 0.3
    patience: 2
    min_lr: 1.0e-7
    warmup_epochs: 5

# Sampling (for Diffusion)
sampling:
  method: "ddim"  # "ddpm" or "ddim"
  ddim_timesteps: 50
  cfg_scale: 2.0
  eta: 0.0

# Hardware
device: "cuda"

